"""Added notifications.

Revision ID: 05e908fba679
Revises: 6d8bad52044b
Create Date: 2023-06-13 20:36:37.080970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05e908fba679'
down_revision = '6d8bad52044b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('notification_text', sa.String(length=100), nullable=True),
    sa.Column('notification_receiver', sa.Integer(), nullable=True),
    sa.Column('notification_is_seen', sa.Boolean(), nullable=True),
    sa.Column('notification_sender_url', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['notification_receiver'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    # ### end Alembic commands ###
