"""Add thread comment

Revision ID: 1399cd2ce6c9
Revises: 0ccab423f7ad
Create Date: 2023-06-05 18:03:31.979490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1399cd2ce6c9'
down_revision = '0ccab423f7ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_parent', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'comments', ['comment_parent'], ['comment_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('comment_parent')

    # ### end Alembic commands ###
