"""Changed relationship in image files

Revision ID: 3464a2bb50bd
Revises: b2de1bf8d8d5
Create Date: 2023-06-10 16:04:51.544490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3464a2bb50bd'
down_revision = 'b2de1bf8d8d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_file')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('file_name',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('file_format',
               existing_type=sa.VARCHAR(length=6),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('file_format',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)
        batch_op.alter_column('file_name',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)

    op.create_table('post_file',
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.file_id'], name='post_file_file_id_fkey'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], name='post_file_post_id_fkey')
    )
    # ### end Alembic commands ###
