"""Create chatrooms.

Revision ID: 43184037f40e
Revises: d02005f6d584
Create Date: 2023-07-01 15:59:09.491892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43184037f40e'
down_revision = 'd02005f6d584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_rooms',
    sa.Column('chatroom_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('chatroom_id')
    )
    op.create_table('chatroom_user',
    sa.Column('chatroom_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chatroom_id'], ['chat_rooms.chatroom_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], )
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_chatroom', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'chat_rooms', ['message_chatroom'], ['chatroom_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('message_chatroom')

    op.drop_table('chatroom_user')
    op.drop_table('chat_rooms')
    # ### end Alembic commands ###
