"""Add image model and image field in other models

Revision ID: b2de1bf8d8d5
Revises: 059ebab336bc
Create Date: 2023-06-09 01:47:53.883201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2de1bf8d8d5'
down_revision = '059ebab336bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=256), nullable=True),
    sa.Column('file_url', sa.String(length=256), nullable=True),
    sa.Column('file_format', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_table('post_file',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.file_id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], )
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_image_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'files', ['comment_image_id'], ['file_id'], ondelete='CASCADE')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_image_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'files', ['post_image_id'], ['file_id'], ondelete='CASCADE')

    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('university_image_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'files', ['university_image_id'], ['file_id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_image_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'files', ['user_image_id'], ['file_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_image_id')

    with op.batch_alter_table('universities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('university_image_id')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('post_image_id')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('comment_image_id')

    op.drop_table('post_file')
    op.drop_table('files')
    # ### end Alembic commands ###
