"""Added created_at for notification

Revision ID: b3dbdeb8cd14
Revises: 05e908fba679
Create Date: 2023-06-13 20:54:00.641069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3dbdeb8cd14'
down_revision = '05e908fba679'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('notification_created_at')

    # ### end Alembic commands ###
