"""Created message model

Revision ID: d02005f6d584
Revises: b3dbdeb8cd14
Create Date: 2023-06-25 16:25:22.880565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd02005f6d584'
down_revision = 'b3dbdeb8cd14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('message_text', sa.String(length=1000), nullable=True),
    sa.Column('message_is_read', sa.Boolean(), nullable=True),
    sa.Column('message_created_at', sa.DateTime(), nullable=True),
    sa.Column('message_edited_at', sa.DateTime(), nullable=True),
    sa.Column('message_sender', sa.Integer(), nullable=True),
    sa.Column('message_receiver', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['message_receiver'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['message_sender'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('notification_text', sa.String(length=100), nullable=True),
    sa.Column('notification_receiver', sa.Integer(), nullable=True),
    sa.Column('notification_is_seen', sa.Boolean(), nullable=True),
    sa.Column('notification_created_at', sa.DateTime(), nullable=True),
    sa.Column('notification_sender_url', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['notification_receiver'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.drop_table('notification')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('notification_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('notification_text', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('notification_receiver', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notification_is_seen', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('notification_sender_url', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('notification_created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['notification_receiver'], ['users.user_id'], name='notification_notification_receiver_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id', name='notification_pkey')
    )
    op.drop_table('notifications')
    op.drop_table('messages')
    # ### end Alembic commands ###
