"""First migration

Revision ID: d06df8133945
Revises: 
Create Date: 2023-04-17 18:53:07.124075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd06df8133945'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universities',
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('university_name', sa.String(length=60), nullable=False),
    sa.Column('university_email', sa.String(length=100), nullable=False),
    sa.Column('university_phone', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('university_id')
    )
    op.create_table('user_roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('faculties',
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('faculty_name', sa.String(length=100), nullable=False),
    sa.Column('faculty_university', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_university'], ['universities.university_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('faculty_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('user_birthday', sa.DateTime(), nullable=True),
    sa.Column('user_tg_link', sa.String(length=200), nullable=True),
    sa.Column('user_enrolment_year', sa.DateTime(), nullable=False),
    sa.Column('user_surname', sa.String(length=50), nullable=False),
    sa.Column('user_card_id', sa.String(length=15), nullable=False),
    sa.Column('user_email', sa.String(length=150), nullable=False),
    sa.Column('user_phone', sa.String(length=50), nullable=True),
    sa.Column('user_password', sa.String(length=50), nullable=True),
    sa.Column('user_role', sa.Integer(), nullable=False),
    sa.Column('user_university', sa.Integer(), nullable=False),
    sa.Column('user_faculty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_faculty'], ['faculties.faculty_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_role'], ['user_roles.role_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_university'], ['universities.university_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_email'),
    sa.UniqueConstraint('user_phone'),
    sa.UniqueConstraint('user_tg_link')
    )
    op.create_table('posts',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('post_heading', sa.String(length=100), nullable=False),
    sa.Column('post_text', sa.String(length=2500), nullable=False),
    sa.Column('post_created_at', sa.DateTime(), nullable=False),
    sa.Column('post_modified_at', sa.DateTime(), nullable=False),
    sa.Column('post_author', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_author'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('comments',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.String(length=500), nullable=False),
    sa.Column('comment_created_at', sa.DateTime(), nullable=False),
    sa.Column('comment_modified_at', sa.DateTime(), nullable=False),
    sa.Column('comment_author', sa.Integer(), nullable=False),
    sa.Column('comment_post', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_author'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['comment_post'], ['posts.post_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('posts')
    op.drop_table('users')
    op.drop_table('faculties')
    op.drop_table('user_roles')
    op.drop_table('universities')
    # ### end Alembic commands ###
