"""Add rating for post model

Revision ID: f7f0b6881f24
Revises: 1399cd2ce6c9
Create Date: 2023-06-07 20:41:53.153948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7f0b6881f24'
down_revision = '1399cd2ce6c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_likes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('post_dislikes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('post_rating', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('post_rating')
        batch_op.drop_column('post_dislikes')
        batch_op.drop_column('post_likes')

    # ### end Alembic commands ###
