from .user import User
from .role import Role
from .university import University
from .faculty import Faculty
from .post import Post
from .comment import Comment
from .file import File
from .notification import Notification
from .message import Message
