MSG_MISSING = "{} field is missing!"
OBJECT_DOES_NOT_EXIST = "{} with an id = {} does not exist!"
OBJECT_DELETED = "{} with an id = {} was successfully deleted!"
OBJECT_EDIT_NOT_ALLOWED = "You are not a creator of this {}, so you can not edit it!"
OBJECT_DELETE_NOT_ALLOWED = "You are not an creator of this {}, so you can not delete it!"
OBJECT_VIEW_NOT_ALLOWED = "You are not allowed to see this {}!"
